### ISSUE TITLE
[Test failure] Active defrag failure to achieve defrag ratio with list

### ISSUE THREAD

**Issue by madolson** [madolson/placeholderkv#1086] opened 2024-09-29 10:31 UTC
*** [err]: Active defrag big list: standalone in tests/unit/memefficiency.tcl
Expected 1.99 < 1.1 (context: type eval line 89 cmd {assert {$frag < 1.1}} proc ::test)

https://github.com/valkey-io/valkey/actions/runs/11079314676/job/30788143655#step:8:6502
https://github.com/valkey-io/valkey/actions/runs/11004472200/job/30555463361#step:6:6478
https://github.com/valkey-io/valkey/actions/runs/10985498040/job/30497443840#step:6:6443
https://github.com/valkey-io/valkey/actions/runs/10976676636/job/30477689950#step:8:6518
https://github.com/valkey-io/valkey/actions/runs/10950803684/job/30406730303#step:8:6500

**Comment by zuiderkwast** [comment] 2024-11-28 23:19
@zvi-code Is this solved by #1370? Or do we need a similar fix? The test failure looks similar.

**Comment by zvi-code** [comment] 2024-11-29 07:28
I see it's 2mo, Is this still happening? 
This is actually very different, because it's a failure to achieve the desired defrag(so it's a real failure in the functionality test of defrag). 

If its still happening I can take a look

**Comment by zuiderkwast** [comment] 2024-11-29 08:40
I don't know if it's still happening. I want to close it...

**Comment by zvi-code** [comment] 2024-11-29 11:48
IMO, it's reasonable to assume same root cause, worse case open new ticket

**Comment by zuiderkwast** [comment] 2024-11-29 12:11
Assumed to be solved by #1370

**Closed as completed by zuiderkwast** 2024-11-29 12:11 UTC
Labels: test-failure
