### ISSUE TITLE
[NEW][Feature Request] TTL for keys within the HASH data type

### ISSUE THREAD

**Issue by Shirkulk007** [madolson/placeholderkv#1003] opened 2024-09-09 06:53 UTC
**The problem/use-case that the feature addresses**

I have encountered few customers use hash data type to store closely associated data where some of the key-value within the HASH change over the time. In order to keep data updated or avoid serving stale data when accessed, they want to configure TTL for each key within the hash. 

**Description of the feature**

Ability to set TTL for keys within the HASH data type.

**Alternatives you've considered**

Move the keys that need the ability to set TLL outside the hash to a separate key

**Additional information**

Any additional information that is relevant to the feature request.

**Comment by hpatro** [comment] 2024-09-09 19:01
@ranshid tagging you, as you mentioned you were exploring this space.

**Comment by madolson** [comment] 2024-09-09 22:34
This is a duplicate of https://github.com/valkey-io/valkey/issues/640.

**Closed as completed by madolson** 2024-09-09 22:34 UTC
