### ISSUE TITLE
[NEW] Add support for expiry of fields in hash key

### ISSUE THREAD

**Issue by tugtugtug** [madolson/placeholderkv#1047] opened 2024-09-18 15:14 UTC
**The problem/use-case that the feature addresses**

There are many cases one would like to have volatile cache entries but also grouped under a hash table. The popular way to workaround it today is to set a timestamp to the hashed value, and manually calculate the expiry.
This is a long asked feature for redis, and redis started the support of it starting 7.4, and forks of it such as KeyDB has supported years ago.

**Description of the feature**

Allow similar expiry that one would set to a key to the hash key(fields)

**Alternatives you've considered**

We currently just carry the timestamp within the value of the key, but obviously this is subject to race and issues like time drift among the clients.

**Additional information**

N/A

**Comment by ranshid** [comment] 2024-09-23 14:37
We should merge the requests in a single place, probably: #640 
@tugtugtug  can you +1 there?

**Comment by tugtugtug** [comment] 2024-09-23 20:47
Thanks @ranshid , agreed, the referenced issue looks identical to my request.

**Comment by ranshid** [comment] 2024-09-24 11:23
ack then I will close this as duplicate

**Comment by ranshid** [comment] 2024-09-24 11:24
duplicate of https://github.com/valkey-io/valkey/issues/640

**Closed as completed by ranshid** 2024-09-24 11:23 UTC
