### ISSUE TITLE
Migrate the build system from make to cmake

### ISSUE THREAD

**Issue by panjf2000** [madolson/placeholderkv#296] opened 2024-04-11 04:24 UTC
I propose migrating the current build system from `make` to `cmake`. 

There are lots of benefits we can gain from the migration, for instance, `CHECK_SYMBOLS_EXIST`.

I'd love to avoid something like:
https://github.com/redis/redis/pull/13005
https://github.com/redis/redis/pull/13104#issuecomment-1975231558

**Comment by zhulipeng** [comment] 2024-04-11 06:38
Similar discussions in https://github.com/valkey-io/valkey/issues/79.

**Comment by zuiderkwast** [comment] 2024-04-11 14:07
Yep, duplicate of #79

**Closed as completed by zuiderkwast** 2024-04-11 14:07 UTC
