### ISSUE TITLE
[NEW] Finalize the TIMEOUT behavior for `CLUSTER SETSLOT`

### ISSUE THREAD

**Issue by PingXie** [madolson/placeholderkv#424] opened 2024-05-02 17:57 UTC
It's better that TIMEOUT 0 doesn't wait at all. It's more logical. Follow-up issue?

_Originally posted by @zuiderkwast in https://github.com/valkey-io/valkey/pull/245#discussion_r1587836830_

**Comment by zuiderkwast** [comment] 2024-05-02 18:15
Duplicate of #422

**Closed as completed** 2024-05-02 21:16 UTC
