### ISSUE TITLE
Multi-Master active-active replication 

### ISSUE THREAD

**Issue by cjabrantes** [madolson/placeholderkv#695] opened 2024-06-25 13:51 UTC
**The problem/use-case that the feature addresses**

For most if not all production scenario HA is a requirement, nevertheless Sentinel or Cluster may be overkill depending on setup size/knowledge/maintenance/complexity

**Description of the feature**

Redis Enterprise, keydb supports this feature (using keydb at the moment) so we can archive HA in a easy and simple way. 

With configuration like:
--multi-master yes 
--active-replica yes 
--replicaof  IP PORT

**Alternatives you've considered**

Cluster and Sentinel are overkill in some scenarios (or may require application changes).
Current Replication needs manual intervention to promote a replica to master

**Additional information**

Can you confirm that this is not support and if yes if there are plans to support it? any ETA?
I would like to use valkey in some k8s deployments, but this feature is required.

Many Thanks!

**Comment by madolson** [comment] 2024-06-25 16:40
Duplicate of https://github.com/valkey-io/valkey/issues/512.

We are looking into it, it's not on the short term roadmap, but we are investigating it.

**Closed as duplicate by madolson** 2024-06-25 16:40 UTC
