### ISSUE TITLE
[NEW] Support for HASH Eviction on basis of Keys & fields, Not only on KEY basis (for Client side caching) 

### ISSUE THREAD

**Issue by atharva29** [madolson/placeholderkv#1130] opened 2024-10-06 06:36 UTC
**The problem/use-case that the feature addresses**

 This will reduce the data transfer between client-side applications & valkey. (client side caching module)

**Description of the feature**

A description of what you want to happen.

Whenver there is a change in hash key. In client side caching, only the hash **field** of client side cache should be changed and should not update the whole **hash key(with other fields)**. This will reduce the data transfer between client-side applications & valkey.

**Alternatives you've considered**
Currently whole Valkey hash key is cleared per hash field change. eg. If my key is user with fields `id`, `address`, `designation`. If I change only one field, the whole Valkey hash key shouldn't get cleared on the client side cache, only the field should be changed.
**Solutions**: We also need to add a field name in the keyspace notification.
https://github.com/redis/jedis/issues/3987

Any alternative solutions or features you've considered, including references to existing open and closed feature requests in this repository.

**Additional information**

Any additional information that is relevant to the feature request.

**Comment by madolson** [comment] 2024-10-06 17:46
Duplicate of https://github.com/valkey-io/valkey/issues/640. Feel free to move any additional context to this issue.

**Closed as not planned by madolson** 2024-10-06 17:46 UTC
